#include "afe4404.h"
#include "main.h"

#ifndef AFE_RESETZ_GPIO_Port
#warning "AFE_RESETZ_GPIO_Port is not defined. Define it in main.h generated by CubeMX."
#endif

static inline uint16_t addr8(const afe4404_t *dev)
{
    return (uint16_t)(dev->i2c_addr_7bit << 1);
}

static inline uint32_t clamp24(uint32_t v)
{
    return (v & 0x00FFFFFFu);
}

// Microsecond delay using DWT cycle counter (Cortex-M4).
// We use this to keep the AFE4404 RESETZ low pulse in the tens of microseconds.
static void afe_delay_us(uint32_t us)
{
    // Enable trace and cycle counter
    if ((CoreDebug->DEMCR & CoreDebug_DEMCR_TRCENA_Msk) == 0) {
        CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
    }
    if ((DWT->CTRL & DWT_CTRL_CYCCNTENA_Msk) == 0) {
        DWT->CYCCNT = 0;
        DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;
    }

    const uint32_t start = DWT->CYCCNT;
    const uint32_t ticks = (SystemCoreClock / 1000000u) * us;
    while ((DWT->CYCCNT - start) < ticks) {
        __NOP();
    }
}

bool afe4404_write24_raw(afe4404_t *dev, uint8_t reg, uint32_t val24)
{
    uint8_t tx[4];
    val24 = clamp24(val24);

    tx[0] = reg;
    tx[1] = (uint8_t)((val24 >> 16) & 0xFF);
    tx[2] = (uint8_t)((val24 >>  8) & 0xFF);
    tx[3] = (uint8_t)((val24 >>  0) & 0xFF);

    return (HAL_I2C_Master_Transmit(dev->hi2c, addr8(dev), tx, 4, 50) == HAL_OK);
}

bool afe4404_read24_raw(afe4404_t *dev, uint8_t reg, uint32_t *val24)
{
    uint8_t rx[3];

    if (HAL_I2C_Master_Transmit(dev->hi2c, addr8(dev), &reg, 1, 50) != HAL_OK) {
        return false;
    }
    if (HAL_I2C_Master_Receive(dev->hi2c, addr8(dev), rx, 3, 50) != HAL_OK) {
        return false;
    }

    *val24 = ((uint32_t)rx[0] << 16) | ((uint32_t)rx[1] << 8) | ((uint32_t)rx[2] << 0);
    *val24 = clamp24(*val24);
    return true;
}

bool afe4404_set_regread(afe4404_t *dev, bool enable)
{
    if (dev == NULL) return false;

    if (dev->reg_read_known && dev->reg_read_cached == enable) {
        return true; // no-op
    }

    uint32_t v = dev->control0_base; // bit0 forced 0 in base
    if (enable) v |= AFE4404_CONTROL0_REGREAD_MASK;

    if (!afe4404_write24_raw(dev, AFE4404_REG_CONTROL0, v)) {
        return false;
    }

    dev->reg_read_cached = enable;
    dev->reg_read_known  = true;
    return true;
}

static inline bool is_data_reg(uint8_t reg)
{
    return (reg >= AFE4404_REG_DATA_START && reg <= AFE4404_REG_DATA_END);
}

bool afe4404_read_cfg24(afe4404_t *dev, uint8_t reg, uint32_t *val24)
{
    if (dev == NULL || val24 == NULL) return false;

    // For data regs, do not toggle REG_READ.
    if (is_data_reg(reg)) {
        return afe4404_read24_raw(dev, reg, val24);
    }

    if (!afe4404_set_regread(dev, true)) {
        return false;
    }
    return afe4404_read24_raw(dev, reg, val24);
}

bool afe4404_write_cfg24(afe4404_t *dev, uint8_t reg, uint32_t val24)
{
    if (dev == NULL) return false;

    // Writes should be done in write-mode (REG_READ=0)
    if (!afe4404_set_regread(dev, false)) {
        return false;
    }
    return afe4404_write24_raw(dev, reg, val24);
}

bool afe4404_read_data24(afe4404_t *dev, uint8_t reg, uint32_t *val24)
{
    if (dev == NULL || val24 == NULL) return false;
    if (!is_data_reg(reg)) return false; // strict (helps catch mistakes)
    return afe4404_read24_raw(dev, reg, val24);
}

bool afe4404_read_auto24(afe4404_t *dev, uint8_t reg, uint32_t *val24)
{
    if (is_data_reg(reg)) return afe4404_read_data24(dev, reg, val24);
    return afe4404_read_cfg24(dev, reg, val24);
}

void afe4404_hw_reset(void)
{
#ifdef AFE_RESETZ_GPIO_Port
    // RESETZ is active-low
    // Datasheet: short LOW pulse = reset, long LOW (>200us) may enter power-down.
    // Here we keep it conservative but not too long.
    HAL_GPIO_WritePin(AFE_RESETZ_GPIO_Port, AFE_RESETZ_Pin, GPIO_PIN_SET);
    HAL_Delay(2);

    HAL_GPIO_WritePin(AFE_RESETZ_GPIO_Port, AFE_RESETZ_Pin, GPIO_PIN_RESET);
    // Keep LOW pulse short to avoid unintended hardware power-down.
    afe_delay_us(30);

    HAL_GPIO_WritePin(AFE_RESETZ_GPIO_Port, AFE_RESETZ_Pin, GPIO_PIN_SET);
    // Datasheet: wait >=1ms before I2C access; give a little margin.
    HAL_Delay(2);
#else
    (void)0;
#endif
}

bool afe4404_apply_regset_from_working_dump(afe4404_t *dev)
{
    // All writes should be in write-mode.
    if (!afe4404_set_regread(dev, false)) return false;

    // ===== CFG =====
    if (!afe4404_write24_raw(dev, 0x21, 0x000005)) return false; // TIA_CFG				// 0x000003
    if (!afe4404_write24_raw(dev, 0x22, 0x0030CF)) return false; // ILED_CFG
    if (!afe4404_write24_raw(dev, 0x23, 0x124018)) return false; // CTRL2

    // ===== TIMING 0x01~0x14 =====
    if (!afe4404_write24_raw(dev, 0x01, 100))  return false;
    if (!afe4404_write24_raw(dev, 0x02, 399))  return false;
    if (!afe4404_write24_raw(dev, 0x03, 802))  return false;
    if (!afe4404_write24_raw(dev, 0x04, 1201)) return false;
    if (!afe4404_write24_raw(dev, 0x05, 501))  return false;
    if (!afe4404_write24_raw(dev, 0x06, 800))  return false;
    if (!afe4404_write24_raw(dev, 0x07, 902))  return false;
    if (!afe4404_write24_raw(dev, 0x08, 1201)) return false;
    if (!afe4404_write24_raw(dev, 0x09, 0))    return false;
    if (!afe4404_write24_raw(dev, 0x0A, 399))  return false;
    if (!afe4404_write24_raw(dev, 0x0B, 1303)) return false;
    if (!afe4404_write24_raw(dev, 0x0C, 1602)) return false;
    if (!afe4404_write24_raw(dev, 0x0D, 409))  return false;
    if (!afe4404_write24_raw(dev, 0x0E, 1468)) return false;
    if (!afe4404_write24_raw(dev, 0x0F, 1478)) return false;
    if (!afe4404_write24_raw(dev, 0x10, 2537)) return false;
    if (!afe4404_write24_raw(dev, 0x11, 2547)) return false;
    if (!afe4404_write24_raw(dev, 0x12, 3606)) return false;
    if (!afe4404_write24_raw(dev, 0x13, 3616)) return false;
    if (!afe4404_write24_raw(dev, 0x14, 4675)) return false;

    // ===== CONV/PRF/PDN =====
    if (!afe4404_write24_raw(dev, 0x15, 401))   return false;   // LED2CONVST
    if (!afe4404_write24_raw(dev, 0x16, 407))   return false;   // LED2CONVEND
    if (!afe4404_write24_raw(dev, 0x17, 1470))  return false;   // ALED2CONVST
    if (!afe4404_write24_raw(dev, 0x18, 1476))  return false;   // ALED2CONVEND
    if (!afe4404_write24_raw(dev, 0x19, 2539))  return false;   // LED1CONVST
    if (!afe4404_write24_raw(dev, 0x1A, 2545))  return false;   // LED1CONVEND

    // ===== additional registers present in the EV (working) dump =====
    // If these are left at reset default (0), the timing engine may not start
    // and ADC_RDY will not toggle after a HW reset.
    if (!afe4404_write24_raw(dev, 0x1B, 0x000E18)) return false; // ADCRSTSTCT3
    if (!afe4404_write24_raw(dev, 0x1C, 0x000E1E)) return false; // ADCRSTENDCT3

    if (!afe4404_write24_raw(dev, 0x1D, 39999)) return false;   // PRPCT (100Hz observed)

    if (!afe4404_write24_raw(dev, 0x20, 0x008005)) return false; // ENSEPGAIN / TIA_GAIN_SEP ...   				//803
    if (!afe4404_write24_raw(dev, 0x31, 0x000020)) return false; // ENABLE_INPUT_SHORT / CLKDIV_EXTMODE			// 0x000005

    if (!afe4404_write24_raw(dev, 0x36, 0x000191)) return false; // LED3LEDSTC
    if (!afe4404_write24_raw(dev, 0x37, 0x000320)) return false; // LED3LEDENDC

    // Dynamic power-down window (as in EV dump)
    if (!afe4404_write24_raw(dev, 0x32, 5475))  return false;   // PDNCYCLESTC
    if (!afe4404_write24_raw(dev, 0x33, 39199)) return false;   // PDNCYCLEENDC

    if (!afe4404_write24_raw(dev, 0x3A, 0X008021)) return false;   // 0ffset

    // Enable timing engine (TIMEREN=1) + averaging (NUMAV=3) as in EV dump.
    // Do this last so all timing parameters are programmed first.
    if (!afe4404_write24_raw(dev, 0x1E, 0x000103)) return false; // TIMEREN/NUMAV

    return true;
}
